# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-09-05 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lbforum', '0003_auto_20200905_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='users_like',
            field=models.CharField(default='[{"userid": 1, "username": 111}, {"userid": 2, "username": 222}]', max_length=2000),
        ),
        migrations.AddField(
            model_name='forum',
            name='users_taken',
            field=models.CharField(default='[{"userid": 1, "username": 111}, {"userid": 2, "username": 222}]', max_length=2000),
        ),
    ]
