# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-09-05 06:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lbforum', '0005_auto_20200905_0630'),
        ('lbforum', '0003_auto_20200905_0621'),
    ]

    operations = [
    ]
