# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-09-05 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lbforum', '0005_auto_20200905_0630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lbforumuserprofile',
            name='classes',
        ),
        migrations.AddField(
            model_name='lbforumuserprofile',
            name='my_like_classes',
            field=models.CharField(default='[1,2]', max_length=2000),
        ),
        migrations.AddField(
            model_name='lbforumuserprofile',
            name='my_taken_classes',
            field=models.CharField(default='[3]', max_length=2000),
        ),
        migrations.AlterField(
            model_name='lbforumuserprofile',
            name='friends',
            field=models.CharField(default='[{"userid": 1, "username": 111}, {"userid": 2, "username": 222}]', max_length=2000),
        ),
    ]
