# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-09-05 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lbforum', '0003_auto_20200905_0621'),
        ('lbforum', '0006_auto_20200905_0737'),
    ]

    operations = [
    ]
