# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-09-05 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lbforum', '0007_merge_20200905_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lbforumuserprofile',
            name='classes',
        ),
        migrations.AlterField(
            model_name='forum',
            name='users_like',
            field=models.CharField(default='[]', max_length=2000),
        ),
        migrations.AlterField(
            model_name='forum',
            name='users_taken',
            field=models.CharField(default='[]', max_length=2000),
        ),
        migrations.AlterField(
            model_name='lbforumuserprofile',
            name='friends',
            field=models.CharField(default='[{"userid": 1, "username": 111}, {"userid": 2, "username": 222}]', max_length=2000),
        ),
        migrations.AlterField(
            model_name='lbforumuserprofile',
            name='my_like_classes',
            field=models.CharField(default='[]', max_length=2000),
        ),
        migrations.AlterField(
            model_name='lbforumuserprofile',
            name='my_taken_classes',
            field=models.CharField(default='[]', max_length=2000),
        ),
    ]
