# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-09-05 08:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lbforum', '0007_auto_20200905_0652'),
        ('lbforum', '0009_auto_20200905_0822'),
    ]

    operations = [
    ]
