# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-09-05 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lbforum', '0010_merge_20200905_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lbforumuserprofile',
            name='friends',
            field=models.CharField(default='[]', max_length=2000),
        ),
        migrations.AlterField(
            model_name='lbforumuserprofile',
            name='my_like_classes',
            field=models.CharField(default='[]', max_length=2000),
        ),
        migrations.AlterField(
            model_name='lbforumuserprofile',
            name='my_taken_classes',
            field=models.CharField(default='[]', max_length=2000),
        ),
    ]
